setwd("~/GitHub/Fall2016-proj3-grp1/data/Project3_poodleKFC_train")
feature_sift<-read.csv("sift_features.csv")
feature_sift_new<-t(feature_sift)
sum(is.na(feature_sift_new))
y <- list.files("images/")
y<- gsub('.{9}$', '', y)
y<-as.numeric(unlist(y) == "dog")
train<-as.data.frame(cbind(feature_sift_new,y))
library(gbm)
library(caret)
gbm.model<-gbm(y~.,data=train,shrinkage=0.01,distribution="bernoulli",cv.folds=5,n.trees=5000,verbose=F)
best.iter<-gbm.perf(gbm.model,method="cv")
summary(gbm.model)
confusionMatrix(predict(gbm.model,train)>0,train$y>0)
