setwd("G:/Columbia/STAT GR5243/project03")
feature_sift<-read.csv("sift_features.csv")
feature_sift_new<-t(feature_sift)
sum(is.na(feature_sift_new))
y<-rep(c(0,1),each=1000)
train<-as.data.frame(cbind(feature_sift_new,y))
library(gbm)
library(caret)
gbm.model<-gbm(y~.,data=train,shrinkage=0.01,distribution="bernoulli",cv.folds=5,n.trees=5000,verbose=F)
best.iter<-gbm.perf(gbm.model,method="cv")
summary(gbm.model)
confusionMatrix(predict(gbm.model,train)>0,train$y>0)
